"""
TestCase + TestCaseVersion ORM models (architecture doc Section 26).
Append-only versioning per Section 23 — same pattern as requirements.

Each test case is scoped to one project and traces back to:
  - requirement_id + requirement_version (traceability chain)
  - application_map_id + state references (which UI states the steps touch)

A test case's steps reference ApplicationMapState state_codes and element_codes
(e.g. STATE-001/EL-005) — never raw CSS selectors. Selector derivation is
Agent 5's job (Automation Generation).
"""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from infra.db.models import Base


class TestCase(Base):
    """Stable identity row — TC-code + pointer to current version + status."""

    __tablename__ = "test_cases"
    __table_args__ = (
        UniqueConstraint("project_id", "tc_code", name="uq_test_cases_project_code"),
    )

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), ForeignKey("projects.id"), nullable=False)
    tc_code: Mapped[str] = mapped_column(String(50), nullable=False)          # e.g. "TC-001"
    requirement_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), ForeignKey("requirements.id"), nullable=False)
    requirement_version: Mapped[int] = mapped_column(Integer, nullable=False)  # pinned version
    application_map_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), ForeignKey("application_maps.id"), nullable=False)
    credential_ref: Mapped[str | None] = mapped_column(String(200), nullable=True)
    account_label: Mapped[str | None] = mapped_column(String(120), nullable=True)
    account_role: Mapped[str | None] = mapped_column(String(120), nullable=True)
    current_version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    # DRAFT | PENDING_APPROVAL | APPROVED | REJECTED
    status: Mapped[str] = mapped_column(String(30), nullable=False, default="DRAFT")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    versions: Mapped[list["TestCaseVersion"]] = relationship(back_populates="test_case")


class TestCaseVersion(Base):
    """
    Append-only. One row per version — never updated after creation.

    steps: ordered list of test steps. Each step:
      {
        "step_number": 1,
        "action": "navigate",          # navigate | fill | click | assert | wait
        "target": {
          "state_code": "STATE-001",
          "element_code": "EL-005",    # references ApplicationMapState.elements[]
          "element_name": "Email",
          "element_role": "textbox"
        },
        "value": "user@example.com",   # for fill actions
        "expected": null               # for assert actions
      }

    test_data: field constraints / data sets generated by Test Data Agent (Agent 7).
      Currently populated by Test Design Agent inline — Agent 7 will extend this.
      {
        "valid": {"email": "user@example.com", "password": "Pass123!"},
        "invalid_email": {"email": "notanemail", "password": "Pass123!"},
        ...
      }

    traceability: which ACs this test case covers.
      ["AC-1", "AC-2"]
    """

    __tablename__ = "test_case_versions"
    __table_args__ = (
        UniqueConstraint("test_case_id", "version", name="uq_test_case_versions_number"),
    )

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    test_case_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), ForeignKey("test_cases.id"), nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    objective: Mapped[str] = mapped_column(Text, nullable=False)
    preconditions: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    steps: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, nullable=False, default=list)
    expected_result: Mapped[str] = mapped_column(Text, nullable=False)
    test_data: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    # Which acceptance criteria from the requirement this TC covers
    traceability: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    # POSITIVE | NEGATIVE | EDGE_CASE | SECURITY | PERFORMANCE
    category: Mapped[str] = mapped_column(String(30), nullable=False, default="POSITIVE")
    # confidence score from the agent
    confidence: Mapped[float] = mapped_column(nullable=False, default=0.0)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    test_case: Mapped["TestCase"] = relationship(back_populates="versions")
